spring:
  application:
    name: team-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/team-management
    username: postgres
    password: 123654
  jpa:
    hibernate:
      ddl-auto: none #create #create-drop
    show-sql: false
    database: PostgreSQL
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:8085}/auth/realms/myrealm/protocol/openid-connect/certs

#  liquibase:
#    change-log: classpath:db/migration/changelog.yaml

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


