spring:
  application:
    name: team-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: head
    password: 456890
  jpa:
    hibernate:
      ddl-auto: update #create
    show-sql: false
#    database: PostgreSQL
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:8085}/auth/realms/myrealm
#          jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:8085}/auth/realms/myrealm/protocol/openid-connect/certs
  cloud:
    config:
      enabled: false

#  liquibase:
#    change-log: classpath:db/migration/changelog.yaml

server:
  port: ${SERVER_PORT:8081}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/


